### ISSUE TITLE
Feedback is array or object

### ISSUE THREAD

**Issue by albsierra** [KA226-COVID/APIs#2]
https://github.com/KA226-COVID/APIs/blob/f24331ecfa563a1b6a9cd7a3a1943a23b6202f40/schemas/YAPEXIL/YAPEXIL.json#L298

When we put some feedback message in Authorkit I suppose it is saved as an array of objects, because we can put mor than one in each test, but in YAPExIL format, feedback property is an object with a message property instead of an array.

**Comment by albsierra** [comment]
I've tried to insert a feedback message in an exercise from Authorkit and feedback-manager return these error messages:
```
feedback-manager_container | [{"instancePath":"/tests/0/feedback","schemaPath":"#/definitions/Test/properties/feedback/type","keyword":"type","params":{"type":"object"},"message":"must be object"}]
feedback-manager_container | TypeError: Cannot read properties of undefined (reading '0')
feedback-manager_container |     at /app/feedback-manager/dist-server/strategies/inputTestCase.js:32:85
feedback-manager_container |     at Array.forEach (<anonymous>)
feedback-manager_container |     at _callee$ (/app/feedback-manager/dist-server/strategies/inputTestCase.js:31:31)
feedback-manager_container |     at tryCatch (/app/feedback-manager/node_modules/regenerator-runtime/runtime.js:63:40)
feedback-manager_container |     at Generator.invoke [as _invoke] (/app/feedback-manager/node_modules/regenerator-runtime/runtime.js:294:22)
feedback-manager_container |     at Generator.next (/app/feedback-manager/node_modules/regenerator-runtime/runtime.js:119:21)
feedback-manager_container |     at asyncGeneratorStep (/app/feedback-manager/dist-server/strategies/inputTestCase.js:7:103)
feedback-manager_container |     at _next (/app/feedback-manager/dist-server/strategies/inputTestCase.js:9:194)
feedback-manager_container |     at /app/feedback-manager/dist-server/strategies/inputTestCase.js:9:364
```

**Comment by zub4t** [comment]
Ok. I will review this. 
Did you try to use more than one feedback for the same test case?

**Comment by albsierra** [comment]
Next is the metadata.json of a test with two feedbacks
```
{
    "id": "a35e2b8d-1186-4056-a986-47e4ce3b2a84",
    "arguments": [
        "undefined"
    ],
    "weight": "1",
    "visible": "true",
    "input": "input.txt",
    "output": "output.txt",
    "timeout": "1",
    "feedback": [
        {
            "message": "Has utilizado insert?",
            "weight": "1"
        },
        {
            "message": "Should you try INSERT query ",
            "weight": "0"
        }
    ]
}
```

**Comment by zub4t** [comment]
OK. the error is regarding the reported issue of the YAPEXIL schema.  I will fix it.

**Comment by zub4t** [comment]
I've already committed the changes in the APIs repository. However, I did not yet verify the correctness of the changes with the feedback manager. Only with the YAPEXIL-CLI and it seems to work correctly.
